#ifndef PHYSICSMOTION_GLOBAL_H
#define PHYSICSMOTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHYSICSMOTION_LIBRARY)
#  define PHYSICSMOTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHYSICSMOTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHYSICSMOTION_GLOBAL_H
